global:
  scrape_interval: 15s

scrape_configs:
  - job_name: flask-app
    static_configs:
      - targets:
          - flask-app:8000

  - job_name: kube-state-metrics
    static_configs:
      - targets:
          - rancher:30080
