apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app
  namespace: observability-demo
  labels:
    release: rancher-monitoring
spec:
  selector:
    matchLabels:
      app: flask-app
  namespaceSelector:
    matchNames:
      - observability-demo
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
