{
 "title": "Flask Observability Dashboard",
 "tags": [
  "flask",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Request Rate (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(request_duration_seconds_count[1m])",
     "legendFormat": "req/sec"
    }
   ]
  },
  {
   "title": "Average Latency (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(request_duration_seconds_sum[5m]) / rate(request_duration_seconds_count[5m])",
     "legendFormat": "avg latency"
    }
   ]
  },
  {
   "title": "Flask App Up",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"flask-app\"}"
    }
   ]
  }
 ]
}